### ISSUE TITLE
Latest build is getting failed. Anyone maintaining this project?

### ISSUE THREAD

**Issue by tyagiamreesh** [grtl/mysql-operator#124]
It seems like no one is maintaining this project as most of the requirement is fulfilled by oracle/mysql-operator now a days.

But I want this operator to run my old MySQL 5.7 instances, which is no longer supported by oracle mysql operator. I tried with their older version 0.1.1, but it's binaries are picking images from wcr.io which is obsolete from oracle side. So oracle/mysql-operator with tag 0.1.1 is also not working for MySQL 5.7.

Please fix it. It would be helpful for those who are looking basic operator for MySQL 5.7.

**Comment by earlgreyz** [comment]
Hey, the builds on Travis are failing due to newer version of minikube. This does not affect the docker image or building the operator itself. I will fix the builds but you can use the operator despite the failing build. As you mentioned oracle/mysql-operator covers most of this project and due to way larger amount of support and developers we've decided not to put our effort in enhancing this project.
